### ISSUE TITLE
显示proxy 你没有设置代理的有效期,请确定你是长效代理,如果是短效代理会导致阶段性请求不可用

### ISSUE THREAD

**Issue by Duoqixiaozei** [bestruirui/RUI_KNOWLEDGE#1]
显示proxy 你没有设置代理的有效期,请确定你是长效代理,如果是短效代理会导致阶段性请求不可用 
是要搞长效代理才能用吗?

**Comment by bestruirui** [comment]
什么？

**Comment by Duoqixiaozei** [comment]
> 什么？

日志显示 ：显示proxy 你没有设置代理的有效期,请确定你是长效代理,如果是短效代理会导致阶段性请求不可用
